# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios
pod 'JSONKit', '~> 1.5pre'
pod 'Reachability', '~> 3.0.0'
pod 'ASIHTTPRequest'
pod 'RegexKitLite'

target '测试CocoaPods' do

end

