
platform:ios, '8.0'
use_frameworks!

target "ObjectiveCDemo20200321" do
# pod 'BaiduMapKit' #百度地图SDK

# 2D地图SDK,NO IDFA版本(3D地图与2D地图不能同时使用)
# pod 'AMap2DMap-NO-IDFA' 

pod 'Masonry'

pod 'AFNetworking', '~> 3.0'

pod 'TTTAttributedLabel'
pod 'YBAttributeTextTapAction'
pod 'TYAttributedLabel'

pod 'FMDB'

#pod 'ReactiveCocoa', '~> 2.5'
pod 'ReactiveObjC', '~> 3.1.0'

pod 'LxDBAnything','~>1.0.0'
pod 'YYModel'

#use_frameworks!
#pod 'XMPPFramework', '~> 3.6.4'
end
